use SqlExercise

CREATE OR ALTER PROCEDURE PAYSLIP 
@EMPNAME VARCHAR(25)
AS
BEGIN
DECLARE @SALARY FLOAT
DECLARE @HRA FLOAT
DECLARE @DA FLOAT
DECLARE @PF FLOAT
DECLARE @IT FLOAT
DECLARE @DEDUCT FLOAT
DECLARE @GROSS_SAL FLOAT
DECLARE @NET_SAL FLOAT

SELECT @SALARY= SAL FROM EMP WHERE Ename=@EMPNAME
--HRA as 10% of Salary 
	SET @HRA = @Salary * 0.1 
--DA as 20% of Salary
    SET @DA = @SALARY* 0.2
--PF as 8% of Salary
    SET @PF = @SALARY * 0.08
-- IT as 5% of Salary
    SET @IT = @SALARY * 0.05
--Deductions as sum of PF and IT
    SET @DEDUCT = @PF + @IT
--Gross Salary as sum of Salary,HRA,DA
    SET @GROSS_SAL = @SALARY + @HRA + @DA
-- Net Salary as Gross Salary - Deductions
    SET @NET_SAL = @GROSS_SAL - @DEDUCT

SELECT  @EMPNAME AS  EMPNAME, @SALARY AS TOTAL_SAL,@HRA AS HRA,@DA AS DA,
@PF AS PF, @IT AS IT , @DEDUCT AS DEDUCATIONS , @GROSS_SAL AS GROSS_SALARY,
@NET_SAL AS NET_SALARY

END

EXEC PAYSLIP 'SMITH'

SELECT* FROM EMP