use SqlExercise

CREATE OR ALTER PROCEDURE PAYSLIP 
@EMPNAME VARCHAR(25)
AS
BEGIN
DECLARE @SALARY FLOAT
DECLARE @HRA FLOAT
DECLARE @DA FLOAT
DECLARE @PF FLOAT
DECLARE @IT FLOAT
DECLARE @DEDUCT FLOAT
DECLARE @GROSS_SAL FLOAT
DECLARE @NET_SAL FLOAT

SELECT @SALARY= SAL FROM EMP WHERE Ename=@EMPNAME
    SET @HRA = 0.10 * @Salary
    SET @DA = 0.20 * @SALARY
    SET @PF = 0.08 * @SALARY
    SET @IT = 0.05 * @SALARY
    SET @DEDUCT = @PF + @IT
    SET @GROSS_SAL = @SALARY + @HRA + @DA
    SET @NET_SAL = @GROSS_SAL - @DEDUCT

SELECT  @EMPNAME AS  EMPNAME, @SALARY AS TOTAL_SAL,@HRA AS HRA,@DA AS DA,
@PF AS PF, @IT AS IT , @DEDUCT AS DEDUCATIONS , @GROSS_SAL AS GROSS_SALARY,
@NET_SAL AS NET_SALARY

END

EXEC PAYSLIP 'SMITH'




